### ISSUE TITLE
Counter vs epoch

### ISSUE THREAD

**Issue by UtCanisAcorio** [jlusPrivat/SimpleHOTP#6]
I'm trying to create a hardware key using your library.  A website I use requirea 2FA with google authenticator, and I believe it is TOTP not HOTP, therefore the "counter" method (I'm guessing) won't work.  Is there a way, if I can get the current Unix epoch 30-second period count, the code can be adapted to use TOTP instead of HOTP?

**Comment by jlusPrivat** [comment]
Yes, you can implement the [TOTP algorithm](https://tools.ietf.org/html/rfc6238). It's fairly simple, as HMAC is already implemented with this library. Unfortunately I am quite busy at the time and can't really help a lot, but please let me know, if you want to create a pull request with the TOTP algorithm!
